# name: DannTeam
name: DannTeam

on:
  workflow_dispatch:
    inputs:
      NGROK_TOKEN:
        description: "Ngrok Auth Token"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/DannOfficial/VpS-Trial/master/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/DannOfficial/VpS-Trial/master/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/DannOfficial/VpS-Trial/master/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/DannOfficial/VpS-Trial/master/loop.bat -OutFile loop.bat
    - name: Download Launcher
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/DannOfficial/VpS-Trial/master/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/DannOfficial/VpS-Trial/master/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: Mengekstrak file
      run: Expand-Archive ngrok.zip
    - name: Masuk ke akun Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_TOKEN
      env:
        NGROK_TOKEN: ${{ github.event.inputs.NGROK_TOKEN }}
    - name: Mengaktifkan akses
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat D:\a\wallpaper.bat
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
    - name: Membuat Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Install Remote Desktop
      run: cmd /c start.bat
    - name: Berhasil di Install!
      run: cmd /c loop.bat
